//! Resource modules

pub mod admissionregistration;
pub use admissionregistration::Admissionregistration;
pub mod mutatingadmissionpolicybinding;
pub use mutatingadmissionpolicybinding::Mutatingadmissionpolicybinding;
pub mod mutatingadmissionpolicie;
pub use mutatingadmissionpolicie::Mutatingadmissionpolicie;
pub mod v1beta1;
pub use v1beta1::V1beta1;
pub mod mutatingadmissionpolicie;
pub use mutatingadmissionpolicie::Mutatingadmissionpolicie;
pub mod mutatingadmissionpolicybinding;
pub use mutatingadmissionpolicybinding::Mutatingadmissionpolicybinding;
pub mod v1alpha1;
pub use v1alpha1::V1alpha1;
pub mod validatingadmissionpolicie;
pub use validatingadmissionpolicie::Validatingadmissionpolicie;
pub mod mutatingwebhookconfiguration;
pub use mutatingwebhookconfiguration::Mutatingwebhookconfiguration;
pub mod validatingadmissionpolicybinding;
pub use validatingadmissionpolicybinding::Validatingadmissionpolicybinding;
pub mod v1;
pub use v1::V1;
pub mod statu;
pub use statu::Statu;
pub mod validatingwebhookconfiguration;
pub use validatingwebhookconfiguration::Validatingwebhookconfiguration;

